//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLPERSONEL
    {
        public byte ID { get; set; }
        [Required(ErrorMessage = "Personel Alanýný Boþ Býrakmayýnýz.")]
        public string PERSONAL { get; set; }
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string MAIL { get; set; }
        [Required(ErrorMessage = "ÞÝfre Alanýný Boþ Býrakmayýnýz.")]
        public string SIFRE { get; set; }
    }
}
